### ISSUE TITLE
how to show the mongo db neatly in browser

### ISSUE THREAD

**Issue by latapata** [matthoiland/restful-api-demo#2]
Hey

First of all I would like to thank you for such a great work. I am a electronics guy not knowing anything about the node.js but i build my server really fast becasue of your video. 

Can you suggest me some method to put the mongodb contents neatly into a html page so that they can be easily visible.

**Comment by matthoiland** [comment]
Hey @latapata. Glad you enjoyed the video.

Your question is out of the scope of this video, but I'm currently planning to put together another video on using Node/MongoDB with the framework [Express](http://expressjs.com/) and the templating engine [Jade](http://jade-lang.com/) that should answer your question. But for now I'd suggest researching Jade and Express. 

Hope this helps!
